### ISSUE TITLE
Mobile version of the website looks really small

### ISSUE THREAD

**Issue by viridis** [RoelandMatthijssens/bazingaWebsite#10] opened 2015-08-03 20:33 UTC
On Iphone the website looks really small. It does not seem to follow the XS section of bootstrap (ie: all pictures are still in 2 colums of 6 width, rather than 1 of 12).

**Comment by RoelandMatthijssens** [comment] 2015-08-03 20:34
Duplicate of #9

**Closed as completed** 2015-08-03 20:33 UTC
Labels: duplicate
